# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/ECE433/Lab7/ECE433/ECE433Lab7Part2/ECE433Lab7Part2.srcs/sources_1/ip/Clock80MHz/Clock80MHz.xci
# IP: The module: 'Clock80MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/ECE433/Lab7/ECE433/ECE433Lab7Part2/ECE433Lab7Part2.srcs/sources_1/ip/Clock80MHz/Clock80MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock80MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/ECE433/Lab7/ECE433/ECE433Lab7Part2/ECE433Lab7Part2.srcs/sources_1/ip/Clock80MHz/Clock80MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock80MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/ECE433/Lab7/ECE433/ECE433Lab7Part2/ECE433Lab7Part2.srcs/sources_1/ip/Clock80MHz/Clock80MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock80MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Xilinx/ECE433/Lab7/ECE433/ECE433Lab7Part2/ECE433Lab7Part2.srcs/sources_1/ip/Clock80MHz/Clock80MHz.xci
# IP: The module: 'Clock80MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/ECE433/Lab7/ECE433/ECE433Lab7Part2/ECE433Lab7Part2.srcs/sources_1/ip/Clock80MHz/Clock80MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock80MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/ECE433/Lab7/ECE433/ECE433Lab7Part2/ECE433Lab7Part2.srcs/sources_1/ip/Clock80MHz/Clock80MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock80MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/ECE433/Lab7/ECE433/ECE433Lab7Part2/ECE433Lab7Part2.srcs/sources_1/ip/Clock80MHz/Clock80MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock80MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
