# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Xilinx/ECE433Fall2024labs/lab7ece433/lab7ece433/.Xil/Vivado-4120-RHIT-R912GGWP/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      {C:/Xilinx/ECE433Fall2024labs/lab7ece433/lab7ece433/lab7ece433.srcs/sources_1/imports/lab7phase1Fall2024source files/DelayLoop2024Fall.v}
      {C:/Xilinx/ECE433Fall2024labs/lab7ece433/lab7ece433/lab7ece433.srcs/sources_1/imports/lab7phase1Fall2024source files/I2C_BaudRateGenerator.v}
      {C:/Xilinx/ECE433Fall2024labs/lab7ece433/lab7ece433/lab7ece433.srcs/sources_1/imports/lab7phase1Fall2024source files/I2C_DataUnit.v}
      {C:/Xilinx/ECE433Fall2024labs/lab7ece433/lab7ece433/lab7ece433.srcs/sources_1/imports/lab7phase1Fall2024source files/I2C_Host_Controller_phase1_temp.v}
      {C:/Xilinx/ECE433Fall2024labs/lab7ece433/lab7ece433/lab7ece433.srcs/sources_1/imports/lab7phase1Fall2024source files/I2C_SDAmodule_temp.v}
      {C:/Xilinx/ECE433Fall2024labs/lab7ece433/lab7ece433/lab7ece433.srcs/sources_1/imports/lab7phase1Fall2024source files/I2C_ShiftRegister.v}
      {C:/Xilinx/ECE433Fall2024labs/lab7ece433/lab7ece433/lab7ece433.srcs/sources_1/imports/lab7phase1Fall2024source files/Lab7I2Cphase1Fall2024JJS.v}
      {C:/Xilinx/ECE433Fall2024labs/lab7ece433/lab7ece433/lab7ece433.srcs/sources_1/imports/lab7phase1Fall2024source files/NegativeClockedOneShot.v}
      {C:/Xilinx/ECE433Fall2024labs/lab7ece433/lab7ece433/lab7ece433.srcs/sources_1/imports/lab7phase1Fall2024source files/PositiveClockedOneShot.v}
      {C:/Xilinx/ECE433Fall2024labs/lab7ece433/lab7ece433/lab7ece433.srcs/sources_1/imports/lab7phase1Fall2024source files/Lab7phase1overall2024fall_tb.v}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top Lab7I2Cphase1fall2024JJS_tb
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Xilinx/ECE433Fall2024labs/lab7ece433/lab7ece433/.Xil/Vivado-4120-RHIT-R912GGWP/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
