# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/ECE433/Term Project/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1.srcs/sources_1/ip/Clock25MHz/Clock25MHz.xci
# IP: The module: 'Clock25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/ECE433/Term Project/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1.srcs/sources_1/ip/Clock25MHz/Clock25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock25MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/ECE433/Term Project/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1.srcs/sources_1/ip/Clock25MHz/Clock25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/ECE433/Term Project/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1.srcs/sources_1/ip/Clock25MHz/Clock25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Xilinx/ECE433/Term Project/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1.srcs/sources_1/ip/Clock25MHz/Clock25MHz.xci
# IP: The module: 'Clock25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/ECE433/Term Project/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1.srcs/sources_1/ip/Clock25MHz/Clock25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/ECE433/Term Project/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1.srcs/sources_1/ip/Clock25MHz/Clock25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/ECE433/Term Project/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1/ECE_433_Term_Project_Phase1.srcs/sources_1/ip/Clock25MHz/Clock25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
